# Generated by Django 5.1.4 on 2024-12-25 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoFilm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='videocontent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KinoFilm.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='created_at',
            field=models.CharField(max_length=100, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='description',
            field=models.TextField(verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KinoFilm.videocontent', verbose_name='Контент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
