# Generated by Django 5.1.4 on 2025-01-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinoFilm', '0004_favoritemovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
