# Generated by Django 5.1.4 on 2025-01-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoFilm', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP пользователя')),
            ],
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='views',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_views', to='KinoFilm.ip', verbose_name='Просмотры'),
        ),
    ]
